### ISSUE TITLE
Re install `components/ui` and copy base from v0

### ISSUE THREAD

**Issue by bacnx** [tranduybau/e-speak-fe#4]

**Comment by tranduybau** [comment]
Issue số 4 mà sao [e-speak-fe-2]? [e-speak-fe-4] chứ

**Comment by tranduybau** [comment]
Commit sai
❌ `feat(base): add basic for app`
✅ `feat(base): [e-speak-fe-4] add basic for app` (đính kèm id issue vào để truy vết sau này)
